apiVersion: v1
kind: Pod
metadata:
 name: hello-world
 annotations:
   "opencontrail.org/network": '[
        {"domain":"default-domain", "project": "default", "name": "right-network"},
        {"domain":"default-domain", "project": "default", "name": "left-network"}
        ]'
 labels:
   app: ubuntuapp
spec:
 containers:
   - name: ubuntuapp
     image: virtualhops/ato-ubuntu:latest
     ports:
     - containerPort: 80
