apiVersion: v1
kind: Pod
metadata:
 name: hello-world
 annotations:
   "opencontrail.org/network": '[
        {"domain":"default-domain", "project": "default", "name": "blue-net"},
        {"domain":"default-domain", "project": "default", "name": "red-net"},
        {"domain":"default-domain", "project": "default", "name": "yellow-net"},
        {"domain":"default-domain", "project": "default", "name": "purple-net"},
        {"domain":"default-domain", "project": "default", "name": "orange-net"}
        ]'
 labels:
   app: ubuntuapp
spec:
 containers:
   - name: ubuntuapp
     image: virtualhops/ato-ubuntu:latest
     ports:
     - containerPort: 80
