apiVersion: v1
kind: Pod
metadata:
  name: serv 
  labels:
    app: ubuntuapp
  annotations:
    networks: '[  
        { "name": "sriov-net1" },
    ]'
spec:
  containers:
    - name: ubuntuapp
      image: virtualhops/ato-ubuntu:latest
      securityContext:
          privileged: true
